name: Application Scheduler

on:
  schedule:
    # 30분마다 실행
    - cron: '*/30 * * * *'
  # 수동 실행 옵션
  workflow_dispatch:
    inputs:
      mode:
        description: '실행 모드'
        required: true
        default: 'PROD'
        type: choice
        options:
          - PROD
          - DEV
      search_keyword:
        description: '검색 키워드'
        required: true
        default: ''

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: JDK 설정
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Maven 캐시 설정
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Maven 빌드 및 종속성 다운로드
      run: |
        mvn clean compile
        
    - name: Application 실행
      env:
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        MODE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode || vars.MODE }}
        SEARCH_KEYWORD: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.search_keyword || vars.SEARCH_KEYWORD }}
      run: |
        mvn exec:java -Dexec.mainClass="Application"
        
    - name: 변경사항 커밋 및 푸시
      uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub에서 제공하는 기본 토큰 사용
      with:
        commit_message: "자동 실행 결과 업데이트: ${{ github.workflow }} at $(date +'%Y-%m-%d %H:%M:%S')"
        commit_user_name: ${{ github.repository_owner }}
        commit_user_email: ${{ github.repository_owner }}@users.noreply.github.com
        commit_author: "${{ github.repository_owner }} <${{ github.repository_owner }}@users.noreply.github.com>"
        add_options: '-A'
        skip_dirty_check: false
